name: CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: cloudsystem.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t cloudsystem.azurecr.io/identity:${{ github.sha }}  -f ITProjectPriceCalculationManager.AuthServer/Dockerfile
        docker push cloudsystem.azurecr.io/identity:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'IdentityManager'
        images: 'cloudsystem.azurecr.io/identity:${{ github.sha }}'
      
    - name: Azure logout
      run:
        az logout