name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  build_dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dotnet
        uses: actions/checkout@v4
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 6.x.x
      
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore
    
  build_docker:
    runs-on: ubuntu-latest
    needs: [build_angular, build_dotnet, build_python]

    steps:
      - name: Checkout docker
        uses: actions/checkout@v4

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
